# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=games.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('directory', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('iframe', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name_plural': 'Games',
            },
        ),
    ]
