# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170114_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytogame',
            old_name='post',
            new_name='game',
        ),
    ]
