# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytopost',
            unique_together=set([]),
        ),
    ]
