# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='video_url',
        ),
    ]
