# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
